version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installin serverless CLI
      - npm i -g serverless
      - echo Installing npm dependencies of notes service
      - npm install
    # steps:
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      - serverless deploy --stage dev
artifacts:
  files:
    - my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'node_modules/**/*'